<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">


	<xacro:property name="sensor_angle_width"  value="0.097" />
	<xacro:property name="sensor_angle_height" value="0.0015" />
	<xacro:property name="sensor_angle_depth"  value="0.0625" />
  
	<xacro:macro name="sensor_angle" params="name parent *origin">
		<link name="${name}_part1_link">
	  		<inertial>
				<mass value="0.01" />
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
	  		</inertial>
	
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${sensor_angle_depth} ${sensor_angle_width} ${sensor_angle_height}"/>
				</geometry>
				<material name="Black" />
			</visual>
	
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${sensor_angle_depth} ${sensor_angle_width} ${sensor_angle_height}"/>
				</geometry>
			</collision >
		</link>

		
		<joint name="${name}_part1_joint" type="fixed">
			<xacro:insert_block name="origin" />
			<parent link="${parent}"/>
			<child link="${name}_part1_link"/>
		</joint>
		
		<link name="${name}_part2_link">
	  		<inertial>
				<mass value="0.01" />
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
	  		</inertial>
	
			<visual>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${sensor_angle_depth} ${sensor_angle_width} ${sensor_angle_height}"/>
				</geometry>
				<material name="Black" />
			</visual>
	
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0" />
				<geometry>
					<box size="${sensor_angle_depth} ${sensor_angle_width} ${sensor_angle_height}"/>
				</geometry>
			</collision >
		</link>

		<joint name="${name}_part2_joint" type="fixed">
			<origin xyz="${-((sensor_angle_depth/2) - (sensor_angle_height/2))} 0 ${((sensor_angle_depth/2) - (sensor_angle_height/2))}" rpy="0 ${M_PI/2} 0 "/>
			<parent link="${name}_part1_link"/>
			<child link="${name}_part2_link"/>
		</joint>
	</xacro:macro>

</root>
