# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: https://github.com/asottile/seed-isort-config
        rev: v1.9.3
        hooks:
            -   id: seed-isort-config

    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
            -   id: isort

    -   repo: https://github.com/ambv/black
        rev: stable
        hooks:
            -   id: black
                language_version: python3.7     # Black requires python3.6 or above to run

    -   repo: https://github.com/pycqa/pylint
        rev: pylint-2.4.4
        hooks:
            -   id: pylint
                entry: pylint --verbose --jobs 4
                language_version: python3.7

    -   repo: https://github.com/pocc/pre-commit-hooks
        rev: python
        hooks:
            -   id: clang-format
                language_version: python3.7

    -   repo: https://github.com/bmorcos/pre-commit-hooks-cpp
        rev: master
        hooks:
            # -   id: cpplint
            -   id: cppcheck


    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.5.0
        hooks:
            -   id: trailing-whitespace
            -   id: check-json
            -   id: check-yaml
            -   id: check-toml
            -   id: check-xml
            -   id: check-merge-conflict
            -   id: mixed-line-ending
            -   id: name-tests-test
                args: ['--django']
            -   id: no-commit-to-branch
                args: [-b, kinetic, -b, melodic]