sudo: required

services:
  - docker

language: cpp

env:
    global:
      - COMPOSE_VERSION: 1.22.0
      - CONTAINER_RELEASE_IMAGE: bitbots/mas_industrial_robotics:$TRAVIS_BRANCH

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - docker-compose -v
  - echo $CONTAINER_RELEASE_IMAGE

stages:
  - build
  - name: deploy
    if: branch IN (devel, indigo, kinetic, melodic) OR tag = true

jobs:
  include:
    - stage: build
      name: "Complete Build"
      script:
        - ./setup.sh full
    - stage: deploy
      name: "Docker Hub Deployment"
      skip_cleanup: true
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker-compose build travis
        - docker images
        - docker push $CONTAINER_RELEASE_IMAGE
