version: '2'
services:
  mas_industrial_robotics:
    build:
      dockerfile: .travis/Dockerfile
      context: .
      args:
        ROS_DISTRO: $ROS_DIST
    image: bitbots/industrial-melodic:$TAG
