version: '2'
services:
  mas_industrial_robotics:
    build:
      dockerfile: images/mas_industrial_robotics/Dockerfile
      context: .
      args:
        ROS_DISTRO: ${ROS_DISTRO}
    image: ghcr.io/b-it-bots/mas_industrial_robotics/industrial-${ROS_DISTRO}:${IMAGE_TAG}
