version: '2'
services:
  travis:
    build:
      dockerfile: .travis/Dockerfile
      context: .
    image: $CONTAINER_RELEASE_IMAGE
  mas_industrial_robotics:
    build:
      dockerfile: .travis/Dockerfile
      context: .
    image: b-it-bots/mas_industrial_robotics
