version: "3.0"
services:
    industrial_melodic:
        image: bitbots/industrial-melodic:latest
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.rviz:/home/robocup/.rviz  # include if any specific rviz settings are needed
        environment:
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROBOT=youbot-brsu-4   # Can be modified here if necessary
            - ROBOT_ENV=brsu-c025-sim # For youbot simulation
        devices:
            - /dev/dri:/dev/dri
        privileged: true
        tty: true
        network_mode: "host"
