#!/usr/bin/env python

import rospy
from brics_actuator.msg import JointPositions
from std_msgs.msg import Empty

CONFIGURATION = None

def pregrasp_planner_cb(msg):
    global CONFIGURATION
    CONFIGURATION = msg

def trigger_cb(msg):
    global CONFIGURATION
    if CONFIGURATION is None:
        rospy.logwarn('Configuration is None')
        return
    pub.publish(CONFIGURATION)
    rospy.loginfo('Published')
    CONFIGURATION = None

if __name__ == '__main__':
    rospy.init_node('move_arm_to_target_conf')

    sub = rospy.Subscriber('/pregrasp_planner_node/joint_configuration', JointPositions, pregrasp_planner_cb)
    trigger_sub = rospy.Subscriber('~trigger', Empty, trigger_cb)
    pub = rospy.Publisher('/arm_moveit_client/target_configuration', JointPositions, queue_size=1)

    rospy.sleep(0.5)
    rospy.loginfo('Initialised')
    rospy.spin()
