<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
       name="youbot" >

  <!-- The following included files set up definitions of parts of the robot body -->
  <!-- misc common stuff -->
  <xacro:include filename="$(find youbot_description)/urdf/common.xacro" />
  <xacro:include filename="$(find mcr_description)/urdf/materials.urdf.xacro" />
  <!-- youbot base and rear platform -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/base.urdf.xacro" />
  <xacro:include filename="$(find mir_description)/urdf/misc/rear_platform_v2.urdf.xacro" />
  <!-- youbot arm and gripper-->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_arm/arm.urdf.xacro"/>
  <xacro:include filename="$(find mir_description)/urdf/misc/full_platform.urdf.xacro" />
  <xacro:include filename="$(find mir_description)/urdf/grippers/dynamixel/v2/dynamixel_gripper.urdf.xacro" />
  <!--xacro:include filename="$(find mir_description)/urdf/grippers/dynamixel/d435_center/dynamixel_gripper.urdf.xacro" /-->
  <!-- controller manager -->
  <xacro:include filename="$(find youbot_description)/controller/ros_controller.urdf.xacro" />
  <!-- materials for visualization -->
  <xacro:include filename="$(find youbot_description)/urdf/materials.urdf.xacro" />
  <!-- sensors -->
  <xacro:include filename="$(find youbot_description)/urdf/sensors/hokuyo_urg04_laser.urdf.xacro"/>
  <xacro:include filename="$(find mir_description)/urdf/sensor_mounts/intel_f200_camera_mount.urdf.xacro"/>
  <xacro:include filename="$(find mcr_description)/urdf/sensors/intel_realsense_f200_camera.urdf.xacro"/>
  <xacro:include filename="$(find mir_description)/urdf/sensors/asus_xtion_camera.urdf.xacro"/>
  <!-- xacro:include filename="$(find mcr_description)/urdf/sensors/realsense_d435.urdf.xacro"/ -->
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>
  <!-- <xacro:include filename="$(find youbot_description)/urdf/sensors/orbbec_astra.urdf.xacro"/> -->
  <xacro:include filename="$(find mir_description)/urdf/sensor_mounts/asus_xtion_camera_mount.urdf.xacro"/>

  <!-- Now we can start using the macros included above to define the actual youbot -->

  <!-- standard youBot configuration -->
  <xacro:youbot_base name="base"/>

  <!-- Arm Plate moving arm 8cm foward and 45 degree rotation -->
  <xacro:full_platform name="full_platform" parent="base_link" arm_angle="${-M_PI / 4}">
    <origin xyz="0.0 0.0 ${0.021 + 0.025 + 0.025}" rpy="0 0 0" />    <!-- ${alignment with base top + spacer height + spacer height } -->
  </xacro:full_platform>

  <xacro:youbot_arm name="arm" parent="full_platform_arm_root_link">
    <origin xyz="-0.022 0.0 0.037" rpy="0 0 0" />
  </xacro:youbot_arm>

  <!-- base laser front -->
  <xacro:hokuyo_urg04_laser name="base_laser_front" parent="base" ros_topic="scan_front" update_rate="10" min_angle="-1.57" max_angle="1.57">
    <origin xyz="0.3 0 -0.035" rpy="${M_PI} 0 0"/>
  </xacro:hokuyo_urg04_laser>

  <!-- base laser rear -->
  <xacro:hokuyo_urg04_laser name="base_laser_rear" parent="base" ros_topic="scan_rear" update_rate="10" min_angle="-1.57" max_angle="1.57" >
     <origin xyz="-0.3 0.0 -0.035" rpy="${M_PI} 0 ${M_PI}" />
  </xacro:hokuyo_urg04_laser>

  <xacro:dynamixel_gripper_v2 name="gripper" parent="arm_link_5">
    <origin xyz="0.003 0 0.0052" rpy="0 0 0" />
  </xacro:dynamixel_gripper_v2>
  
  <!-- tower front camera -->
  <xacro:sensor_d435 name="tower_cam3d_front_camera" parent="tower_camera_front_bolt_link" use_nominal_extrinsics="true">
      <!-- <origin xyz="0.035 0.020 0.0" rpy="0.0 1.22 0.0" /> -->
      <origin xyz="0.01 0.025 0.0" rpy="0.0 1.22 0.0" />  
  </xacro:sensor_d435>

  <!-- tower middle camera -->
  <!-- <xacro:sensor_orbbec_astra  name="tower_cam3d_middle" parent="base_link" color="">
    <origin xyz="0.15 -0.06225 0.775" rpy="0 ${M_PI/2} ${-M_PI/2}" />
  </xacro:sensor_orbbec_astra> -->

  <!-- tower back camera -->
  <xacro:sensor_d435  name="tower_cam3d_back_camera" parent="tower_camera_back_bolt_link" use_nominal_extrinsics="true">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.78 0.0" />
  </xacro:sensor_d435>

   <!-- tower vertical mount link -->

  <link name="tower_camera_stand_link">
    <visual>
      <geometry>
        <box size="0.030 0.030 0.80"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.030 0.030 0.80"/>
      </geometry>
    </collision>
  </link>

  <joint name="tower_camera_stand_joint" type="fixed">
    <origin xyz="-0.10 0.0 0.40" rpy="0 0 0" />
    <parent link="full_platform_link"/>
    <child link="tower_camera_stand_link"/>
  </joint>

  <!-- link for emergency stop mount with stl mesh file -->
  <link name="emergency_stop_mount_link">
    <visual>
      <geometry>
        <mesh filename="package://mir_description/meshes/misc/e_stop_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual>
    <!-- <collision>
      <geometry>
        <mesh filename="package://mir_description/meshes/misc/e_stop_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision> -->
  </link>

  <joint name="emergency_stop_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 0.40" rpy="${pi/2} 0 0" />
    <parent link="tower_camera_stand_link"/>
    <child link="emergency_stop_mount_link"/>
  </joint>

  <!-- tower horizontal mount link -->
  <link name="tower_camera_stand_link_horizontal">
    <visual>
      <geometry>
        <box size="0.030 0.030 0.608"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.030 0.030 0.608"/>
      </geometry>
    </collision>
  </link>

  <joint name="tower_camera_stand_joint_horizontal" type="fixed">
    <origin xyz="0.09 -0.035 0.362" rpy="0 ${M_PI/2} 0" />
    <parent link="tower_camera_stand_link"/>
    <child link="tower_camera_stand_link_horizontal"/>
  </joint>

  <link name="tower_camera_stand_link_horizontal_front" />

  <joint name="tower_camera_stand_joint_horizontal_front" type="fixed">
    <origin xyz="0.0 0.0 0.304" rpy="0 -${M_PI/2} 0" />
    <parent link="tower_camera_stand_link_horizontal"/>
    <child link="tower_camera_stand_link_horizontal_front"/>
  </joint>

  <link name="tower_camera_stand_link_horizontal_back" />

  <joint name="tower_camera_stand_joint_horizontal_back" type="fixed">
    <origin xyz="0.0 0.0 -0.304" rpy="${M_PI} 0 0" />
    <parent link="tower_camera_stand_link_horizontal"/>
    <child link="tower_camera_stand_link_horizontal_back"/>
  </joint>

  <!-- tower front camera mount link -->
  <link name="tower_camera_front_mount_link">
    <visual>
      <geometry>
        <mesh filename="package://mir_description/meshes/sensor_mounts/intel_camera_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual>
    <!-- <collision>
      <geometry>
        <mesh filename="package://mir_description/meshes/sensor_mounts/intel_camera_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision> -->
  </link>

  <joint name="tower_camera_front_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} ${M_PI} 0" />
    <parent link="tower_camera_stand_link_horizontal_front"/>
    <child link="tower_camera_front_mount_link"/>
  </joint> 

  <link name="tower_camera_front_bolt_link" />
  <!-- final joint values = xyz="0.016645 0.0 0.028855 " (middle of 2 holes) +  xyz="0.0125 0.0 -0.009 " (distance from holes to bolt)-->
  <joint name="tower_camera_front_bolt_joint" type="fixed">
    <!-- Middle of camera back plate <origin xyz="0.028855 0.0 -0.016645" rpy="0 0 0" /> --> 
    <origin xyz="0.019855 0.0 -0.029145" rpy="0 0 0" />
    <parent link="tower_camera_stand_link_horizontal_front"/>
    <child link="tower_camera_front_bolt_link"/>
  </joint>  

  <!-- tower back camera mount link -->
  <link name="tower_camera_back_mount_link">
    <visual>
      <geometry>
        <!-- <mesh filename="package://mir_description/meshes/sensor_mounts/intel_camera_mount.STL" scale="0.001 0.001 0.001"/> -->
        <mesh filename="package://mir_description/meshes/sensor_mounts/intel_camera_mount_back.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual>
    <!-- <collision>
      <geometry>
        <mesh filename="package://mir_description/meshes/sensor_mounts/intel_camera_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision> -->
  </link>

  <joint name="tower_camera_back_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="-${M_PI} ${M_PI/2} -${M_PI/2}" />
    <parent link="tower_camera_stand_link_horizontal_back"/>
    <child link="tower_camera_back_mount_link"/>
  </joint>

  <link name="tower_camera_back_bolt_link" />
  <!-- final joint values = xyz="0.02121 0.00 0.02250 " (middle of 2 holes) +  xyz="0.0125 0.0 -0.009 " (distance from holes to bolt)-->
  <joint name="tower_camera_back_bolt_joint" type="fixed">
    <origin xyz="0.00871 0.0 0.03150" rpy="0 -1.57 0" />
    <!-- <origin xyz="0.029145 0.0 0.019855" rpy="0 -0.37 0" /> -->
    <parent link="tower_camera_stand_link_horizontal_back"/>
    <child link="tower_camera_back_bolt_link"/>
  </joint> 

  <!-- tower side camera mount link -->
  <!-- <link name="tower_camera_side_mount_link">
    <visual>
      <geometry>
        <mesh filename="package://mir_description/meshes/sensor_mounts/side_camera_mount.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
          <color rgba="0.85098 0.85098 0.85098 1"/>
      </material>
    </visual> 
  </link> 
  
  <joint name="tower_camera_side_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 0.149" rpy="${M_PI/2} -${M_PI/2} 0" />
    <parent link="tower_camera_stand_link_horizontal"/>
    <child link="tower_camera_side_mount_link"/>
  </joint> -->

</robot>
