;This PDDL costs were generated automatically from perception cost generator node
(= (perception-complexity AXIS) 10)
(= (perception-complexity BEARING) 2)
(= (perception-complexity BEARING_BOX) 13)
(= (perception-complexity DISTANCE_TUBE) 2)
(= (perception-complexity F20_20_B) 20)
(= (perception-complexity F20_20_G) 2)
(= (perception-complexity M20) 2)
(= (perception-complexity M20_100) 20)
(= (perception-complexity M30) 20)
(= (perception-complexity MOTOR) 20)
(= (perception-complexity R20) 20)
(= (perception-complexity S40_40_B) 20)
(= (perception-complexity S40_40_G) 6)