#!/usr/bin/env python

from __future__ import print_function

import rospy

from mir_atwork_commander_client.atwork_commander_client import AtworkCommanderClient

NODE = "mir_atwork_commander_client"

if __name__ == "__main__":
    rospy.init_node(NODE)
    ACC = AtworkCommanderClient()
    rospy.spin()
