<?xml version="1.0"?>
<root xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:include filename="$(find youbot_description)/urdf/sensors/asus_xtion_camera.gazebo.xacro" />
  
  <xacro:property name="eye_x_offset" value="0.03" />
  <xacro:property name="eye_y_offset" value="0.035" />
  
  <xacro:macro name="asus_xtion_eye" params="suffix parent *origin">
	<link name="${parent}_${suffix}_frame">
	  <inertial>
		<mass value="0.01" />
		<origin xyz="0 0 0" />
		<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
	  </inertial>	
	</link>
	
	<joint name="${parent}_${suffix}_joint" type="fixed">
	  <parent link="${parent}_link"/>
	  <child link="${parent}_${suffix}_frame"/>
	  <xacro:insert_block name="origin"/>
	</joint>		
  </xacro:macro>
    
  <xacro:macro name="asus_xtion_camera" params="name parent *origin ">
    <link name="${name}_link">
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0.02 -0.03 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
        <geometry>
          <mesh filename="package://mcr_description/meshes/sensors/asus_xtion_pro_live_camera.dae" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Black" />
      </visual>

      <collision>
        <origin xyz="0.02 -0.03 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
        <geometry>
           <mesh filename="package://mcr_description/meshes/sensors/asus_xtion_pro_live_camera_convexhull.dae" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision >
    </link>
    
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
    

    <xacro:asus_xtion_eye suffix="depth" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.02} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
        
	<xacro:asus_xtion_eye suffix="depth_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.02} 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="rgb" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.04} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="rgb_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.04} 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="laser" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.09} 0" rpy="0 0 0" />
	</xacro:asus_xtion_eye>
	
	<xacro:asus_xtion_eye suffix="laser_optical" parent="${name}">
		<origin xyz="${eye_x_offset} ${eye_y_offset - 0.09} 0" rpy="${M_PI/2} 0 ${-M_PI/2}" />
	</xacro:asus_xtion_eye>

    
   <!-- for simulation -->
   <xacro:asus_xtion_camera_gazebo name="${name}" />

  </xacro:macro>

</root>
