#!/usr/bin/python

import roslib
import rospy

import actionlib

from move_base_msgs.msg import MoveBaseAction

class MoveBaseMockup(object):
  
  def __init__(self):
    self._as = actionlib.SimpleActionServer("move_base", MoveBaseAction, execute_cb=self.execute_cb, auto_start = False)
    self._as.start()
    
  def execute_cb(self, goal):
    self._as.set_succeeded()
      
if __name__ == '__main__':
  rospy.init_node('mir_move_base_mockup')
  MoveBaseMockup()
  rospy.loginfo("move_base MOCKUP started...")
  rospy.spin()