#!/usr/bin/python

import roslib
import rospy

import actionlib

from move_base_msgs.msg import MoveBaseAction
from std_srvs.srv import *

class MoveBaseMockup(object):
  
  def __init__(self):
    self._as = actionlib.SimpleActionServer("move_base", MoveBaseAction, execute_cb=self.execute_cb, auto_start = False)
    self._as.start()
    s = rospy.Service('/move_base/clear_costmaps', Empty, self.clear_costmap_cb)


  def execute_cb(self, goal):
    rospy.sleep(1)
    self._as.set_succeeded()

  def clear_costmap_cb(self, req):
    rospy.loginfo("clear costmaps")
    rospy.sleep(1)    
    return EmptyResponse()

      
if __name__ == '__main__':
  rospy.init_node('mir_move_base_mockup')
  MoveBaseMockup()
  rospy.loginfo("move_base MOCKUP started...")
  rospy.spin()
