/arm_moveit_client/event_in
/arm_moveit_client/event_out
/barrier_tape/scan
/base_motion_calculator/event_in
/base_motion_calculator/event_out
/base_motion_calculator/pose_out_1
/dashboard/platform_state
/dashboard/power_state
/diagnostics
/gripper_controller/grasp_monitor/event_in
/gripper_controller/grasp_monitor/event_out
/gripper_moveit_client/event_in
/gripper_moveit_client/event_out
/insert_object_in_cavity_server/cancel
/insert_object_in_cavity_server/feedback
/insert_object_in_cavity_server/goal
/insert_object_in_cavity_server/result
/insert_object_in_cavity_server/status
/insert_object_server/cancel
/insert_object_server/feedback
/insert_object_server/goal
/insert_object_server/result
/insert_object_server/status
/knowledge_base_analyzer/pending_goals/event_in
/knowledge_base_analyzer/pending_goals/event_out
/map
/mcr_common/dynamic_reconfigure_client/event_in
/mcr_common/dynamic_reconfigure_client/event_out
/mcr_common/twist_to_motion_direction_conversion/event_in
/mcr_navigation/collision_velocity_filter/event_out
/mcr_navigation/direct_base_controller/coordinator/event_in
/mcr_navigation/direct_base_controller/coordinator/event_out
/mcr_navigation/direct_base_controller/pose_converter/converted_pose
/mcr_navigation/direct_base_controller/pose_converter/event_in
/mcr_navigation/direct_base_controller/pose_error_calculator/event_in
/mcr_navigation/direct_base_controller/pose_error_calculator/event_out
/mcr_navigation/direct_base_controller/pose_error_monitor/event_in
/mcr_navigation/direct_base_controller/pose_error_monitor/event_out
/mcr_navigation/direct_base_controller/twist_controller/event_in
/mcr_navigation/direct_base_controller/twist_controller/event_out
/mcr_navigation/direct_base_controller/twist_limiter/event_in
/mcr_navigation/direct_base_controller/twist_limiter/event_out
/mcr_navigation/direct_base_controller/twist_synchronizer/event_in
/mcr_navigation/direct_base_controller/twist_synchronizer/event_out
/mir_perception/barrier_tape_detection/event_in
/mcr_perception/cavity_finder/input/event_in
/mcr_perception/cavity_finder/output/depth_debug_image
/mcr_perception/cavity_finder/output/event_out
/mcr_perception/cavity_finder/output/pointclouds
/mcr_perception/cavity_finder/output/pointclouds_combined
/mcr_perception/cavity_finder/output/pose
/mcr_perception/cavity_finder/output/rgb_debug_image
/mcr_perception/cavity_pose_selector/cavity
/mcr_perception/cavity_pose_selector/event_in
/mcr_perception/cavity_pose_selector/event_out
/mcr_perception/cavity_pose_selector/object_name
/mcr_perception/cloud_accumulator/event_in
/mcr_perception/cloud_accumulator/event_out
/mcr_perception/cloud_accumulator/output
/mcr_perception/convex_hull/output
/mcr_perception/convex_hull/output_polygon
/mcr_perception/multimodal_object_identification/input/event_in
/mcr_perception/multimodal_object_identification/input/recognized_objects_list
/mcr_perception/multimodal_object_identification/output/event_out
/mcr_perception/multimodal_object_identification/output/platform_pointcloud
/mcr_perception/multimodal_object_identification/output/pointclouds_combined
/mcr_perception/multimodal_object_identification/output/pose
/mcr_perception/multimodal_object_identification/output/rgb_debug_image
/mcr_perception/multimodal_object_identification/output/segmented_object_debug_image
/mcr_perception/mux_pointcloud/event_in
/mcr_perception/mux_pointcloud/event_out
/mcr_perception/object_detector/event_in
/mcr_perception/object_detector/event_out
/mcr_perception/object_detector/object_list
/mcr_perception/object_list_merger/event_in
/mcr_perception/object_list_merger/event_out
/mcr_perception/object_list_merger/output_object_list
/mcr_perception/object_selector/event_in
/mcr_perception/object_selector/event_out
/mcr_perception/object_selector/input/object_name
/mcr_perception/object_selector/output/object
/mcr_perception/object_selector/output/object_name
/mcr_perception/object_selector/output/object_pose
/mcr_perception/place_pose_selector/event_in
/mcr_perception/place_pose_selector/event_out
/mcr_perception/place_pose_selector/place_pose
/mcr_perception/place_pose_selector/platform_name
/mcr_perception/tabletop_cloud_accumulator/accumulated_cloud
/mcr_perception/tabletop_cloud_clusterer/tabletop_clusters
/mcr_perception/transform/output
/mcr_perception/workspace_finder/event_in
/mcr_perception/workspace_finder/event_out
/mcr_perception/workspace_finder/polygon
/mcr_task_planning/mercury_planner/event_in
/mcr_task_planning/mercury_planner/event_out
/mcr_tools/rosbag_recorder/event_in
/mir_knowledge_base_analyzer/knowledge_base_queries/event_out
/mir_knowledge_base_analyzer/knowledge_base_queries/objects_at_location
/mir_knowledge_base_analyzer/knowledge_base_queries/query
/mir_knowledge_base_analyzer/knowledge_base_queries/query_param
/mir_knowledge_base_analyzer/knowledge_base_queries/robot_location
/mir_manipulation/look_at_point/event_in
/mir_pregrasp_planner_pipeline/pose_out
/move_arm_planned/event_in
/move_arm_planned/event_out
/move_arm_planned/joint_position_monitor/configuration
/move_arm_planned/joint_position_monitor/event_in
/move_arm_planned/joint_position_monitor/event_out
/move_arm_planned_motion/event_in
/move_base/DWAPlannerROS/global_plan
/move_base/DWAPlannerROS/local_plan
/move_base/GlobalPlannerWithOrientations/plan
/move_base/GlobalPlannerWithOrientations/potential
/move_base/cancel
/move_base/current_goal
/move_base/feedback
/move_base/force_field_recovery/force_field_vector
/move_base/force_field_recovery/obstacle_cloud
/move_base/force_field_recovery/obstacle_neighborhood
/move_base/global_costmap/costmap
/move_base/goal
/move_base/local_costmap/costmap
/move_base/result
/move_base/status
/move_base_safe_server/cancel
/move_base_safe_server/feedback
/move_base_safe_server/goal
/move_base_safe_server/result
/move_base_safe_server/status
/move_base_simple/goal
/move_base_wrapper/event_in
/move_base_wrapper/event_out
/move_base_wrapper/pose_in
/move_base_wrapper/pose_out
/move_group/cancel
/odom
/particlecloud
/perceive_cavity_server/cancel
/perceive_cavity_server/feedback
/perceive_cavity_server/goal
/perceive_cavity_server/result
/perceive_cavity_server/status
/perceive_location_server/cancel
/perceive_location_server/feedback
/perceive_location_server/goal
/perceive_location_server/result
/perceive_location_server/status
/place_object_server/cancel
/place_object_server/feedback
/place_object_server/goal
/place_object_server/result
/place_object_server/status
/pregrasp_pipeline_pose_selector/event_in
/pregrasp_pipeline_pose_selector/event_out
/pregrasp_pipeline_pose_selector/goal_pose
/pregrasp_pipeline_pose_selector/joint_configuration
/pregrasp_pipeline_pose_selector/joint_configuration_prepregrasp
/pregrasp_pipeline_pose_selector/offset_pose
/pregrasp_planner_pipeline/event_in
/pregrasp_planner_pipeline/event_out
/pregrasp_planner_pipeline/grasp_planner/event_in
/pregrasp_planner_pipeline/grasp_planner/event_out
/pregrasp_planner_pipeline/grasp_planner/pose_out
/pregrasp_planner_pipeline/grasp_planner/sampling_parameters
/pregrasp_planner_pipeline/grasp_type
/pregrasp_planner_pipeline/pose_generator/event_in
/pregrasp_planner_pipeline/pose_generator/event_out
/pregrasp_planner_pipeline/pose_generator/poses_list
/pregrasp_planner_pipeline/pose_transformer/event_in
/pregrasp_planner_pipeline/pose_transformer/event_out
/pregrasp_planner_pipeline/pose_transformer/transformed_pose
/realsense_node/health_status
/refbox_parser/event_in
/refbox_parser/event_out
/rosout
/rosout_agg
/scan_combined
/scan_front
/scan_rear
/stage_object_server/cancel
/stage_object_server/feedback
/stage_object_server/goal
/stage_object_server/result
/stage_object_server/status
/static_transform_publisher_node/event_in
/task_planning/execute_plan/cancel
/task_planning/execute_plan/feedback
/task_planning/execute_plan/goal
/task_planning/execute_plan/result
/task_planning/execute_plan/status
/task_planning/load_plan/cancel
/task_planning/load_plan/feedback
/task_planning/load_plan/goal
/task_planning/load_plan/result
/task_planning/load_plan/status
/task_planning/pddl_problem_generator_node/event_in
/task_planning/pddl_problem_generator_node/event_out
/task_planning/plan_success_analizer/event_in
/task_planning/plan_success_analizer/event_out
/tf
/tf_static
/unstage_object_server/cancel
/unstage_object_server/feedback
/unstage_object_server/goal
/unstage_object_server/result
/unstage_object_server/status
/upload_knowledge/event_in
/visualization_marker
/visualization_marker_array
/waypoint_trajectory_generation/event_in
/waypoint_trajectory_generation/event_out
/wbc/mcr_navigation/direct_base_controller/coordinator/event_in
/wbc/mcr_navigation/direct_base_controller/coordinator/event_out
/wbc/mcr_navigation/direct_base_controller/pose_error_calculator/event_in
/wbc/mcr_navigation/direct_base_controller/pose_error_calculator/event_out
/wbc/mcr_navigation/direct_base_controller/pose_error_monitor/event_in
/wbc/mcr_navigation/direct_base_controller/pose_error_monitor/event_out
/wbc/mcr_navigation/direct_base_controller/pose_transformer_trigger/event_in
/wbc/mcr_navigation/direct_base_controller/twist_controller/event_in
/wbc/mcr_navigation/direct_base_controller/twist_controller/event_out
/wbc/mcr_navigation/direct_base_controller/twist_limiter/event_in
/wbc/mcr_navigation/direct_base_controller/twist_limiter/event_out
/wbc/mcr_navigation/direct_base_controller/twist_synchronizer/event_in
/wbc/mcr_navigation/direct_base_controller/twist_synchronizer/event_out
/wbc_base_motion_calculator_pipeline/pose_transformer/transformed_pose
/wbc_pick_object_server/cancel
/wbc_pick_object_server/feedback
/wbc_pick_object_server/goal
/wbc_pick_object_server/result
/wbc_pick_object_server/status
/whole_body_motion_calculator_pipeline/event_in
/whole_body_motion_calculator_pipeline/event_out
/whole_body_motion_calculator_pipeline/pose_out
/whole_body_motion_calculator_pipeline/pose_selector/event_in
/whole_body_motion_calculator_pipeline/pose_selector/event_out
/whole_body_motion_calculator_pipeline/pose_transformer/event_in
/whole_body_motion_calculator_pipeline/pose_transformer/event_out
/whole_body_motion_calculator_pipeline/pose_transformer/transformed_pose
/whole_body_motion_calculator_pipeline/whole_body_motion_calculator/event_in
/whole_body_motion_calculator_pipeline/whole_body_motion_calculator/event_out
/mir_perception/barrier_tape_detection/output/yellow_barrier_tape_pose_array
