pregrasp_laying_object:
    /pregrasp_planner_pipeline/grasp_planner:
      min_azimuth: -3.0
      max_azimuth: 3.0
      min_zenith: -3.0
      max_zenith: 3.0
      min_roll: 0.0
      max_roll: 0.0
lift_object:
    /poses_to_move_wrtbase/move_wrtbase_pose_shifter:
      linear_offset_x: 0.0
      linear_offset_y: 0.0
      linear_offset_z: 0.08
