pick_normal_pregrasp:
    /pregrasp_planner_pipeline/grasp_planner:
      min_azimuth: -6.0
      max_azimuth: 6.0
      min_zenith: -6.0
      max_zenith: 6.0
      min_roll: 0.0
      max_roll: 0.0
top_hole_pregrasp:
    /top_hole_pregrasp_planner_pipeline/grasp_planner:
      min_azimuth: -3.0
      max_azimuth: 3.0
      min_zenith: -50.0
      max_zenith: 3.0
      min_roll: 0.0
      max_roll: 0.0
move_up_shifter:
    /poses_to_move/move_pose_shifter:
      linear_offset_x: 0.0
      linear_offset_y: 0.0
      linear_offset_z: 0.05
move_down_shifter:
    /poses_to_move/move_pose_shifter:
      linear_offset_x: 0.0
      linear_offset_y: 0.0
      linear_offset_z: -0.03
top_hole_shifter:
    /top_hole_pose_shifter:
      linear_offset_x: 0.0
      linear_offset_y: 0.0
      linear_offset_z: 0.1
close_range_camera_perception:
    /realsense_node:
      motion_range_trade_off: 100
far_range_camera_barrier_tape:
    /realsense_node:
      motion_range_trade_off: 50
