# This file is used to specify parameters that can be set
# using dynamic reconfigure. The named configurations set here
# can be referred to from state machines in order to change a set of parameters
# for a particular node based on the context. For example dbc_move_base
# consists of all parameters for the direct base controller which is
# used by the move_base wrapper. dbc_pick_object consists of the parameters for the
# same direct base controller, but used in the context of picking objects (or inserting)
dbc_move_base:
    /mcr_navigation/direct_base_controller/coordinator:
        threshold_linear_x: 0.005
        threshold_linear_y: 0.005
        threshold_angular_z: 0.04
        wait_for_transform: 0.1
        p_gain_x: 3.0
        p_gain_y: 3.0
        p_gain_yaw: 3.0
        max_velocity_x: 0.35
        max_velocity_y: 0.35
        max_velocity_z: 0.0
        max_velocity_roll: 0.0
        max_velocity_pitch: 0.0
        max_velocity_yaw: 0.35
        use_collision_avoidance: False
        loop_rate: 20.0
dbc_pick_object:
    /mcr_navigation/direct_base_controller/coordinator:
        threshold_linear_x: 0.04
        threshold_linear_y: 0.02
        threshold_angular_z: 15.0
        wait_for_transform: 0.1
        p_gain_x: 2.0
        p_gain_y: 4.0
        p_gain_yaw: 4.0
        max_velocity_x: 0.05
        max_velocity_y: 0.2
        max_velocity_z: 0.0
        max_velocity_roll: 0.0
        max_velocity_pitch: 0.0
        max_velocity_yaw: 0.4
        use_collision_avoidance: True
        front_laser_threshold: 0.04
        right_laser_threshold: 0.1
        rear_laser_threshold: 0.1
        left_laser_threshold: 0.04
        loop_rate: 25.0
pregrasp_planner_single_shot:
    /pregrasp_planner_node:
        min_azimuth: 0.0
        max_azimuth: 0.0
        min_zenith: 0.0
        max_zenith: 0.0
        min_roll: 0.0
        max_roll: 0.0
        linear_step: 0.01
        angular_step: 0.5
        min_distance_to_object: -0.03
        max_distance_to_object: -0.03
        max_samples: 20
        max_height: 0.0
        min_height: 0.0
        height_tolerance: 0.24
        angular_tolerance: 10.0
        target_frame: base_link
        reference_axis: z
        rotation_offset: 0.0
        linear_offset_x: 0.0
        linear_offset_y: 0.0
        linear_offset_z: 0.0
        generate_pregrasp_waypoint: True
        ignore_orientation: False
        joint_1_offset: 0.0
        joint_2_offset: -0.6
        joint_3_offset: 0.3
        joint_4_offset: 0.0
        joint_5_offset: 0.0
        joint_1_offset_side_grasp: 0.0
        joint_2_offset_side_grasp: 0.0
        joint_3_offset_side_grasp: 0.453
        joint_4_offset_side_grasp: -0.367
        joint_5_offset_side_grasp: 0.0
        rotation_range_min: 270.0
        rotation_range_max: 90.0
pregrasp_planner_pick:
    /pregrasp_planner_node:
        min_azimuth: 0.0
        max_azimuth: 0.0
        min_zenith: -5.0
        max_zenith: 5.0
        min_roll: -30.0
        max_roll: 30.0
pregrasp_planner_no_sampling:
    /pregrasp_planner_node:
        min_azimuth: 0.0
        max_azimuth: 0.0
        min_zenith: 0.0
        max_zenith: 0.0
        min_roll: 0.0
        max_roll: 0.0
pregrasp_planner_zealous:
    /pregrasp_planner_node:
        min_azimuth: 0.0
        max_azimuth: 0.0
        min_zenith: -60.0
        max_zenith: 10.0
        min_roll: -30.0
        max_roll: 30.0
        linear_step: 0.01
        angular_step: 0.5
        min_distance_to_object: 0.0
        max_distance_to_object: 0.0
        max_samples: 20
        max_height: 0.0
        min_height: 0.0
        max_samples: 20
        max_height: 0.0
        min_height: 0.0
        target_frame: base_link
        ignore_orientation: True
multimodal_object_recognition_atwork:
    /mir_perception/multimodal_object_recognition:
        obj_category: atwork
        rgb_cluster_filter_limit_max: 0.35
multimodal_object_recognition_cavity:
    /mir_perception/multimodal_object_recognition:
        obj_category: cavity
        rgb_cluster_filter_limit_max: -0.015
multimodal_object_recognition_container:
    /mir_perception/multimodal_object_recognition:
        obj_category: container
        rgb_cluster_filter_limit_max: 0.35
