# This file is used to specify parameters that can be set
# using dynamic reconfigure. The named configurations set here
# can be referred to from state machines in order to change a set of parameters
# for a particular node based on the context. For example dbc_move_base
# consists of all parameters for the direct base controller which is
# used by the move_base wrapper. dbc_pick_object consists of the parameters for the
# same direct base controller, but used in the context of picking objects (or inserting)
dbc_move_base:
    /mcr_navigation/direct_base_controller/coordinator:
        threshold_linear_x: 0.005
        threshold_linear_y: 0.005
        threshold_angular_z: 0.04
        wait_for_transform: 0.1
        p_gain_x: 3.0
        p_gain_y: 3.0
        p_gain_yaw: 3.0
        max_velocity_x: 0.35
        max_velocity_y: 0.35
        max_velocity_z: 0.0
        max_velocity_roll: 0.0
        max_velocity_pitch: 0.0
        max_velocity_yaw: 0.35
        use_collision_avoidance: False
        loop_rate: 20.0
dbc_pick_object:
    /mcr_navigation/direct_base_controller/coordinator:
        threshold_linear_x: 0.04
        threshold_linear_y: 0.02
        threshold_angular_z: 15.0
        wait_for_transform: 0.1
        p_gain_x: 2.0
        p_gain_y: 4.0
        p_gain_yaw: 4.0
        max_velocity_x: 0.05
        max_velocity_y: 0.2
        max_velocity_z: 0.0
        max_velocity_roll: 0.0
        max_velocity_pitch: 0.0
        max_velocity_yaw: 0.4
        use_collision_avoidance: True
        front_laser_threshold: 0.04
        right_laser_threshold: 0.04
        rear_laser_threshold: 0.02
        left_laser_threshold: 0.04
        loop_rate: 25.0
