# =======
# MOVE_BASE
# =======
move_base:
    color: 
        r: 0.3
        g: 0.9
        b: 0.3
        a: 0.6
# =======
# PICK
# =======
pick:
    color: 
        r: 0.3
        g: 0.9
        b: 0.3
        a: 0.6 
    scale: 0.0012
