#!/usr/bin/env python

import rospy

from mir_controller_msgs.srv import StartVisualServoing, StartVisualServoingResponse
from mir_controller_msgs.msg import VisualServoingState

def _do_visual_servoing_cb(request):
    rospy.loginfo("Do visual servoing MOCKUP called")
    
    response = StartVisualServoingResponse()
    
    response.return_value.error_code = VisualServoingState.SUCCESS
    
    return response

if __name__ == '__main__':
    rospy.init_node("do_visual_servoing_cb")

    s = rospy.Service('~do_visual_servoing', StartVisualServoing, _do_visual_servoing_cb)
    rospy.loginfo('do_visual_servoing service MOCKUP started')
        
    rospy.spin()
