# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_joint_1:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  arm_joint_2:
    has_velocity_limits: true
    max_velocity: 1.309
    has_acceleration_limits: true
    max_acceleration: 1.2
  arm_joint_3:
    has_velocity_limits: true
    max_velocity: 1.5707
    has_acceleration_limits: true
    max_acceleration: 1.5707
  arm_joint_4:
    has_velocity_limits: true
    max_velocity: 2.0944
    has_acceleration_limits: true
    max_acceleration: 1.571
  arm_joint_5:
    has_velocity_limits: true
    max_velocity: 2.0944
    has_acceleration_limits: true
    max_acceleration: 1.571
  gripper_motor_left_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: true
    max_acceleration: 1.5
  gripper_motor_right_joint:
    has_velocity_limits: true
    max_velocity: 6.178465545
    has_acceleration_limits: true
    max_acceleration: 1.5
