<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find mcr_description)/urdf/sensors/intel_realsense_f200_camera.gazebo.xacro" />

  <xacro:property name="eye_x_offset" value="-0.015" />   
  <xacro:property name="eye_y_offset" value="0.024" />  
  <xacro:property name="eye_z_offset" value="0.018" />

  <xacro:macro name="intel_realsense_f200_eye" params="suffix parent *origin">
	<link name="${parent}_${suffix}_frame">
	  <inertial>
		<mass value="0.0001" />
		<origin xyz="0 0 0" />
		<inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
	  </inertial>	
	</link>
	
	<joint name="${parent}_${suffix}_joint" type="fixed">
	  <parent link="${parent}_link"/>
	  <child link="${parent}_${suffix}_frame"/>
	  <xacro:insert_block name="origin"/>
	</joint>		
  </xacro:macro>


  <xacro:macro name="intel_realsense_f200_camera" params="name parent *origin">
    <link name="${name}_link">
      <inertial>
        <mass value="0.170" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
      </inertial>

      <visual>
        <origin xyz="0 -0.074 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mcr_description/meshes/sensors/intel_realsense_f200_camera.dae" scale="0.001 0.001 0.001" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0 -0.074 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mcr_description/meshes/sensors/intel_realsense_f200_camera_convex_hull.dae" scale="0.001 0.001 0.001" />
        </geometry>
     </collision>
    </link>

    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}_link"/>
    </joint>
 
    <xacro:intel_realsense_f200_eye suffix="depth" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset - 0.048} ${eye_z_offset}" rpy="0 0 0" />
    </xacro:intel_realsense_f200_eye>
        
    <xacro:intel_realsense_f200_eye suffix="depth_optical" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset - 0.048} ${eye_z_offset}" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    </xacro:intel_realsense_f200_eye>

    <xacro:intel_realsense_f200_eye suffix="rgb" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset - 0.024} ${eye_z_offset}" rpy="0 0 0" />
    </xacro:intel_realsense_f200_eye>

    <xacro:intel_realsense_f200_eye suffix="rgb_optical" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset - 0.024} ${eye_z_offset}" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
    </xacro:intel_realsense_f200_eye>

    <xacro:intel_realsense_f200_eye suffix="laser" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset} ${eye_z_offset}" rpy="0 0 0" />
    </xacro:intel_realsense_f200_eye>

    <xacro:intel_realsense_f200_eye suffix="laser_optical" parent="${name}">
      <origin xyz="${eye_x_offset} ${eye_y_offset} ${eye_z_offset}" rpy="${M_PI/2} 0 ${-M_PI/2}" />
    </xacro:intel_realsense_f200_eye>
  
     <!-- for simulation -->
     <xacro:intel_realsense_f200_camera_gazebo name="${name}" />
     
   </xacro:macro>

</root>
