robot_base_frame: base_link

update_frequency: 3.0
publish_frequency: 3.0

transform_tolerance: 0.5
obstacle_range: 4.5
raytrace_range: 5.0

static:
    map_topic: /map
    subscribe_to_updates: true

obstacle_layer:
    observation_sources: laser_scanner_front laser_scanner_rear
    laser_scanner_front:
        sensor_frame: base_laser_front_link
        data_type: LaserScan
        topic: /scan_front
        expected_update_rate: 1.2
        observation_persistence: 0.0
        marking: true
        clearing: true
        min_obstacle_height: -0.10
        max_obstacle_height: 2.0
    laser_scanner_rear: 
        sensor_frame: base_laser_rear_link
        data_type: LaserScan
        topic: /scan_rear
        expected_update_rate: 1.2
        observation_persistence: 0.0
        marking: true
        clearing: true
        min_obstacle_height: -0.10
        max_obstacle_height: 2.0

inflation:
    inflation_radius: 0.3
